import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { PageHeader } from '../components/ui/PageHeader'
import { Button } from '../components/ui/Button'
import { EmptyState } from '../components/ui/EmptyState'
import { DemoBanner } from '../components/domain/ModeBanners'
import { AdaptiveLoop } from '../components/domain/AdaptiveLoop'
import { AdaptiveInsight } from '../components/domain/AdaptiveInsight'
import { getQuizBank, hasRealQuestions } from '../services/quiz'
import { useAppData } from '../hooks/useAppData'
import { useAppState } from '../context/AppState'
import { api } from '../services/api'

export function QuizPage() {
  const data = useAppData()
  const { setupCompleted, session } = useAppState()
  const bank = getQuizBank()
  const navigate = useNavigate()
  
  // Backend-loaded topics
  const [backendSubjects, setBackendSubjects] = useState([])
  const [backendTopics, setBackendTopics] = useState([])
  const [loadingTopics, setLoadingTopics] = useState(true)
  const [topicError, setTopicError] = useState('')
  
  const [subjectId, setSubjectId] = useState('')
  const [topicId, setTopicId] = useState('')
  const [questionCount, setQuestionCount] = useState(10)
  const [generating, setGenerating] = useState(false)
  const [generationStatus, setGenerationStatus] = useState('')

  // Load topics from backend on mount
  useEffect(() => {
    async function loadTopics() {
      setLoadingTopics(true)
      setTopicError('')
      try {
        const result = await api.get('/ai/syllabus-topics')
        // api.get returns json.data directly
        console.log('[Quiz] Topics API response:', result)
        if (result?.subjects) {
          setBackendSubjects(result.subjects || [])
          setBackendTopics(result.topics || [])
        } else {
          console.warn('[Quiz] No subjects in response:', result)
        }
      } catch (err) {
        // Fallback to local data
        console.error('[Quiz] Failed to load topics:', err.message)
        setBackendSubjects([])
        setBackendTopics([])
        setTopicError('Could not load topics from server. Using local data.')
      }
      setLoadingTopics(false)
    }
    loadTopics()
  }, [session?.token])

  // Auto-generate topics from subject names when no syllabus exists
  const [autoGenerated, setAutoGenerated] = useState(false)
  const [generatingTopics, setGeneratingTopics] = useState(false)

  // Use backend topics if available, fallback to workspace subjects
  const subjects = backendSubjects.length > 0 ? backendSubjects : (data.subjects || [])
  const topics = backendTopics.length > 0 ? backendTopics : (data.topics || [])
  
  const topicOptions = topics.filter((t) => !subjectId || t.subjectId === subjectId)

  useEffect(() => {
    if (!subjectId && subjects[0]?.id) setSubjectId(subjects[0].id)
  }, [subjects, subjectId])

  useEffect(() => {
    if (!topicOptions.some((t) => t.id === topicId)) {
      setTopicId(topicOptions[0]?.id || '')
    }
  }, [topicOptions, topicId])

  const selectedTopic = topics.find((t) => t.id === topicId) || topicOptions[0]
  const selectedSubject = subjects.find((s) => s.id === subjectId)

  function startDemo() {
    sessionStorage.setItem(
      'eduvance.quiz.config',
      JSON.stringify({ kind: 'demo', subject: bank.subject, topic: bank.topic, count: 10, minutes: 15 }),
    )
    navigate('/quiz/play')
  }

  function startCheck() {
    const topic = selectedTopic
    if (!topic) return
    const subjectName = topic.subjectName || topic.subject || subjects.find(s => s.id === topic.subjectId)?.name || ''
    sessionStorage.setItem(
      'eduvance.quiz.config',
      JSON.stringify({
        kind: 'check',
        subject: subjectName,
        subjectId: topic.subjectId,
        topic: topic.name,
        topicId: topic.id,
        count: questionCount,
        minutes: Math.max(15, questionCount * 1.5),
      }),
    )
    navigate('/quiz/play')
  }

  async function startBatchQuiz() {
    const topic = selectedTopic
    if (!topic) return
    const subjectName = topic.subjectName || topic.subject || subjects.find(s => s.id === topic.subjectId)?.name || ''
    
    setGenerating(true)
    setGenerationStatus(`Generating ${questionCount} questions about ${topic.name}...`)
    
    try {
      // Use batch endpoint for larger counts
      if (questionCount > 15) {
        const result = await api.post('/ai/generate-quiz-batch', {
          subject: subjectName,
          topic: topic.name,
          difficulty: 'medium',
          totalQuestions: questionCount,
          batchSize: 10,
        })
        
        // api.post returns json.data directly (unwrapped)
        if (result?.questions?.length > 0) {
          setGenerationStatus(`Generated ${result.totalGenerated} questions!`)
          // Store and navigate to quiz
          sessionStorage.setItem(
            'eduvance.quiz.config',
            JSON.stringify({
              kind: 'check',
              subject: subjectName,
              subjectId: topic.subjectId,
              topic: topic.name,
              topicId: topic.id,
              count: result.totalGenerated,
              minutes: Math.max(15, result.totalGenerated * 1.5),
              useBackendQuestions: true,
            }),
          )
          navigate('/quiz/play')
        } else {
          setGenerationStatus('Generation failed. Using local questions.')
          startCheck()
        }
      } else {
        startCheck()
      }
    } catch (err) {
      setGenerationStatus('AI unavailable. Using local questions.')
      startCheck()
    }
    setGenerating(false)
  }

  const hasBankQuestions = selectedTopic && (() => {
    const subjName = selectedTopic.subjectName || selectedTopic.subject || subjects.find(s => s.id === selectedTopic.subjectId)?.name || ''
    return hasRealQuestions(subjName, selectedTopic.name)
  })()

  if (!data.isDemo && !setupCompleted) {
    return (
      <EmptyState
        title="Complete setup to begin adaptive preparation."
        body="Quiz uses the subjects and topics from your preparation — it will not ask for a timetable."
        action={
          <Button as={Link} to="/setup">
            Open setup
          </Button>
        }
      />
    )
  }

  // Auto-generate topics when no syllabus exists but subjects are configured
  async function autoGenerateTopics() {
    const subjectNames = data.subjects?.map(s => s.name).filter(Boolean) || []
    if (subjectNames.length === 0) return
    setGeneratingTopics(true)
    try {
      const allTopics = []
      const allSubjects = []
      for (const name of subjectNames) {
        try {
          const result = await api.post('/ai/generate-topics', { subject: name })
          if (result?.topics?.length) {
            allTopics.push(...result.topics)
            allSubjects.push({ id: result.topics[0]?.subjectId || name, name: result.subject || name, topicCount: result.topics.length })
          }
        } catch (err) {
          console.error(`[Quiz] Failed to generate topics for ${name}:`, err.message)
        }
      }
      if (allTopics.length > 0) {
        setBackendSubjects(allSubjects)
        setBackendTopics(allTopics)
        setAutoGenerated(true)
      }
    } catch (err) {
      setTopicError('AI topic generation failed. Make sure GROQ_API_KEY is on Render.')
    }
    setGeneratingTopics(false)
  }

  // Auto-generate on mount if no topics exist but subjects are configured
  useEffect(() => {
    if (!autoGenerated && !loadingTopics && backendTopics.length === 0 && !generatingTopics) {
      const subjectNames = data.subjects?.map(s => s.name).filter(Boolean) || []
      if (subjectNames.length > 0) autoGenerateTopics()
    }
  }, [loadingTopics])

  if (generatingTopics) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <div className="mb-4 h-10 w-10 animate-spin rounded-full border-4 border-accent border-t-transparent" />
        <p className="text-sm text-ink-2">AI is generating quiz topics from your subjects...</p>
        <p className="mt-1 text-xs text-ink-3">This takes a few seconds per subject</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Study → quiz → evaluate → replan"
        subtitle="Eduvance already knows your subjects. A quiz writes evidence into the same preparation state."
      />

      <AdaptiveLoop compact />

      {data.isDemo && (
        <DemoBanner
          body="You're exploring Eduvance without an account. Sign up to unlock personalized quizzes."
          action={
            <Button as={Link} to="/register?intent=prepare" size="sm">
              Create account
            </Button>
          }
        />
      )}

      {/* Topic selector */}
      {!data.isDemo && subjects.length > 0 && (
        <div className="mt-8 max-w-xl space-y-4">
          <h2 className="font-medium text-ink">Quiz from your preparation</h2>
          <p className="text-sm text-ink-2">
            {backendSubjects.length > 0 
              ? 'Topics loaded from your uploaded syllabus.' 
              : 'Subjects and topics come from your setup.'}
          </p>

          {loadingTopics && (
            <div className="flex items-center gap-2 text-sm text-ink-3">
              <span className="animate-spin">⏳</span> Loading topics from syllabus...
            </div>
          )}

          {topicError && (
            <p className="text-xs text-amber-600">{topicError}</p>
          )}

          {/* Subject selector */}
          <div>
            <label className="block text-xs font-medium uppercase tracking-wider text-ink-3 mb-1">
              Choose subject
            </label>
            <select
              value={subjectId}
              onChange={(e) => setSubjectId(e.target.value)}
              className="input w-full"
            >
              {subjects.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name} ({s.topicCount || topicOptions.filter(t => t.subjectId === s.id).length} topics)
                </option>
              ))}
            </select>
          </div>

          {/* Topic selector */}
          <div>
            <label className="block text-xs font-medium uppercase tracking-wider text-ink-3 mb-1">
              Choose topic
            </label>
            <select
              value={topicId}
              onChange={(e) => setTopicId(e.target.value)}
              className="input w-full"
            >
              {topicOptions.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name} {t.difficulty ? `(${t.difficulty})` : ''}
                </option>
              ))}
            </select>
            {topicOptions.length > 0 && (
              <p className="mt-1 text-[10px] text-ink-3">
                {topicOptions.length} topic{topicOptions.length !== 1 ? 's' : ''} available for {selectedSubject?.name || 'this subject'}
              </p>
            )}
          </div>

          {/* Question count */}
          <div>
            <label className="block text-xs font-medium uppercase tracking-wider text-ink-3 mb-1">
              Number of questions
            </label>
            <select
              value={questionCount}
              onChange={(e) => setQuestionCount(Number(e.target.value))}
              className="input w-full"
            >
              <option value={5}>5 questions (quick check)</option>
              <option value={10}>10 questions (standard)</option>
              <option value={20}>20 questions (thorough)</option>
              <option value={50}>50 questions (comprehensive)</option>
              <option value={100}>100 questions (full bank)</option>
            </select>
          </div>

          {/* Start quiz button */}
          <div className="flex items-center gap-3">
            <Button
              onClick={questionCount > 15 ? startBatchQuiz : startCheck}
              disabled={!selectedTopic || generating}
            >
              {generating ? 'Generating...' : `Start quiz →`}
            </Button>
            <span className="text-[11px] text-ink-3">
              🎯 AI-generated from your syllabus
            </span>
          </div>

          {generationStatus && (
            <p className="text-xs text-accent-2">{generationStatus}</p>
          )}
        </div>
      )}

      {/* Adaptive loop */}
      {!data.isDemo && (
        <div className="mt-12">
          <AdaptiveInsight
            title="How Eduvance adapts"
            body="Your quiz performance feeds the priority engine. Weak topics rise; mastered topics step back."
          />
        </div>
      )}
    </div>
  )
}
